quasimodo_website/models/search_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField


class SearchForm(FlaskForm):

    subject = StringField("Subject")
    predicate = StringField("Predicate")
    object = StringField("Object")
    modality = StringField("Modality")
    polarity = SelectField("Polarity",
                           choices=[("Positive and Negative",
                                     "Positive and Negative"),
                                    ("Positive", "Positive"),
                                    ("Negative", "Negative")])
    search = SubmitField("Search")

quasimodo_website/codenames/__init__.py
from quasimodo_website.codenames import routes

quasimodo_website/codenames/blueprint.py
from flask import Blueprint

BP = Blueprint('codenames', __name__)

quasimodo_website/codenames/routes.py
import os

from flask import render_template, session, request, jsonify

from quasimodo_website.codenames.blueprint import BP
from quasimodo_website.codenames.codenames import Codenames, CodenameColor
from quasimodo_website.codenames.codenames_agents import CodenamesMaster, Clue
from quasimodo_website.codenames.stop_the_game_players import \
    StopTheGameOperative, WaitForActionException, ClueGivenException, \
    QuasimodoSpyMasterWhenStopping

CODENAMES_FILE = FILENAME = os.path.dirname(os.path.realpath(__file__)) + \
                            "/../tests/codenames_words.txt"


@BP.route("/")
def home():
    codenames = Codenames.from_filename(CODENAMES_FILE)
    codenames_master = CodenamesMaster(
        codenames,
        red_spymaster=QuasimodoSpyMasterWhenStopping(
            codenames,
            CodenameColor.RED),
        red_operative=StopTheGameOperative(codenames,
                                           CodenameColor.RED,
                                           None,
                                           False)
    )
    return _play(codenames, codenames_master)


def _play(codenames, codenames_master):
    try:
        codenames_master.run_game()
    except WaitForActionException as _:
        session["codenames"] = codenames.to_json()
        return render_template("codenames.html",
                               codenames=codenames,
                               message="Choose another card")
    except ClueGivenException as e:
        session["codenames"] = codenames.to_json()
        clue = e.clue
        session["clue"] = str(clue.word) + "," + str(clue.occurrences)
        message = "Clue Given: " + str(clue.word) + ", " + str(
            clue.occurrences)
        return render_template("codenames.html",
                               codenames=codenames,
                               message=message)
    session["codenames"] = codenames.to_json()
    return render_template(
        "codenames_full.html",
        codenames=codenames,
        message="Game ended, winner is " + str(codenames.get_winner().name))


@BP.route("/guess_word")
def guess_word():
    guessed_word = request.args.get('word', None, type=str)
    codenames_json = session.get("codenames", None)
    if codenames_json is None:
        return jsonify({"error": "No game was started"})
    if guessed_word is None:
        return jsonify({"error": "No word was given"})
    codenames = Codenames.from_json(codenames_json)
    current_clue = session.get("clue", None)
    if codenames.has_played_already or current_clue is None:
        current_clue = None
    else:
        word, occ = current_clue.split(",")
        current_clue = Clue(word, occ)
    codenames_master = CodenamesMaster(
        codenames,
        red_spymaster=QuasimodoSpyMasterWhenStopping(
            codenames,
            CodenameColor.RED,
            word_given=current_clue),
        red_operative=StopTheGameOperative(codenames,
                                           CodenameColor.RED,
                                           guessed_word,
                                           False)
    )
    return _play(codenames, codenames_master)


@BP.route("/pass")
def pass_turn():
    codenames_json = session.get("codenames", None)
    if codenames_json is None:
        return jsonify({"error": "No game was started"})
    codenames = Codenames.from_json(codenames_json)
    codenames_master = CodenamesMaster(
        codenames,
        red_spymaster=QuasimodoSpyMasterWhenStopping(
            codenames,
            CodenameColor.RED),
        red_operative=StopTheGameOperative(codenames,
                                           CodenameColor.RED,
                                           None,
                                           True)
    )
    return _play(codenames, codenames_master)

quasimodo_website/explorer/__init__.py
from quasimodo_website.explorer import routes

quasimodo_website/explorer/blueprint.py
from flask import Blueprint

BP = Blueprint('explorer', __name__)

quasimodo_website/explorer/routes.py
import os

from flask import render_template, request, url_for, jsonify
from flask import current_app as app
from sqlalchemy import desc, asc
from werkzeug.utils import redirect

from quasimodo_website import DB, get_ip
from quasimodo_website.explorer.blueprint import BP
from quasimodo_website.models.fact import Fact, read_facts, add_all_facts_to_db
from quasimodo_website.models.fact_feedback import FactFeedback
from quasimodo_website.models.search_form import SearchForm


@BP.route("/")
def home():
    page = request.args.get('page', 1, type=int)
    order_str = request.args.get("order", "pd", type=str)
    order = get_order(order_str)
    subject = request.args.get("subject", None, type=str)
    predicate = request.args.get("predicate", None, type=str)
    obj = request.args.get("object", None, type=str)
    modality = request.args.get("modality", None, type=str)
    polarity = request.args.get("polarity", None, type=str)
    if polarity is not None:
        polarity = polarity == "1"

    facts = Fact.query
    if subject:
        facts = facts.filter_by(subject=subject)
    if predicate:
        facts = facts.filter_by(predicate=predicate)
    if obj:
        facts = facts.filter_by(object=obj)
    if modality:
        search_regex = "%{}%".format(modality)
        facts = facts.filter(Fact.modality_like(search_regex))
    if polarity is not None:
        facts = facts.filter_by(is_negative=polarity)

    n_facts = facts.count()
    facts = facts.order_by(order).paginate(page,
                                           app.config["FACTS_PER_PAGE"],
                                           False)
    new_args = request.args.copy()
    new_args["page"] = facts.next_num
    next_url = url_for('explorer.home', **new_args) if facts.has_next else None
    new_args["page"] = facts.prev_num
    prev_url = url_for('explorer.home', **new_args) if facts.has_prev else None
    if "page" in new_args:
        del new_args["page"]
    if "order" in new_args:
        del new_args["order"]
    return render_template("explorer.html", facts=facts.items,
                           next_url=next_url,
                           prev_url=prev_url,
                           order=order_str,
                           n_facts=n_facts,
                           additional_args=new_args)


def get_order(order_str):
    if order_str == "pd":
        order = desc(Fact.plausibility)
    elif order_str == "pa":
        order = asc(Fact.plausibility)
    elif order_str == "td":
        order = desc(Fact.neighborhood_sigma)
    elif order_str == "ta":
        order = asc(Fact.neighborhood_sigma)
    elif order_str == "sd":
        order = desc(Fact.local_sigma)
    elif order_str == "sa":
        order = asc(Fact.local_sigma)
    else:
        order = desc(Fact.plausibility)
    return order


@BP.route("/fill")
def fill():
    facts = read_facts(os.path.abspath(os.path.dirname(__file__)) +
                       "/../tests/quasimodo_sample.tsv")
    add_all_facts_to_db(facts, DB)
    return "Done"


@BP.route("/search", methods=["GET", "POST"])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        args = {}
        if form.subject.data.strip():
            args["subject"] = form.subject.data.strip().lower()
        if form.predicate.data.strip():
            args["predicate"] = form.predicate.data.strip().lower()
        if form.object.data.strip():
            args["object"] = form.object.data.strip().lower()
        if form.modality.data.strip():
            args["modality"] = form.modality.data.strip().lower()
        if form.polarity.data == "Positive":
            args["polarity"] = 0
        elif form.polarity.data == "Negative":
            args["polarity"] = 1

        args["page"] = request.args.get('page', 1, type=int)
        args["order"] = request.args.get("order", "pd", type=str)
        return redirect(url_for("explorer.home", **args))
    return render_template("search.html", form=form)


@BP.route("/fact")
def get_fact():
    fact_id = request.args.get('id', None, type=int)
    if fact_id is not None:
        fact = Fact.query.get(fact_id)
        if fact is not None:
            return render_template("fact_details.html", fact=fact)
    return redirect(url_for("homepage.home"))


@BP.route("/feedback")
def give_feedback():
    fact_id = request.args.get("id", None, type=int)
    feedback = request.args.get("feedback", None, type=str)
    if fact_id is None or feedback is None:
        return jsonify({"error": "Wrong id or feedback."})
    fact_feedback = FactFeedback(fact_id=fact_id,
                                 source=get_ip(),
                                 feedback=feedback)
    DB.session.add(fact_feedback)
    DB.session.commit()
    return jsonify({"message": "We thank you for your feedback :)"})

quasimodo_website/homepage/__init__.py
from quasimodo_website.homepage import routes

quasimodo_website/homepage/blueprint.py
from flask import Blueprint

BP = Blueprint('homepage', __name__)

quasimodo_website/homepage/routes.py
import urllib.request
import zipfile

from flask import render_template, url_for, current_app, request
from werkzeug.utils import redirect

from quasimodo_website import DB
from quasimodo_website.homepage.blueprint import BP
from quasimodo_website.models import Fact
from quasimodo_website.models.fact import read_facts_from_file, \
    add_all_facts_to_db


@BP.route("/")
def home():
    return render_template("main_page.html")


@BP.route("/initialize")
def initialize():
    n_facts = Fact.query.count()
    if n_facts == 0:
        url = request.args.get("url",
                               'https://www.mpi-inf.mpg.de/fileadmin/inf/'
                               'd5/research/quasimodo/quasimodo-v1.2.zip',
                               type=str)
        current_app.logger.info("Downloading Quasimodo...")
        file_handle, _ = urllib.request.urlretrieve(url)
        current_app.logger.info("Unzipping Quasimodo...")
        zip_file_object = zipfile.ZipFile(file_handle, 'r')
        first_file = zip_file_object.namelist()[0]
        file = zip_file_object.open(first_file, 'r')
        current_app.logger.info("Reading facts...")
        facts = read_facts_from_file(file)
        current_app.logger.info("Filling database...")
        add_all_facts_to_db(facts, DB, limit_insert=10000)
        current_app.logger.info("Initialization done")
        return "Initialization done"
    return redirect(url_for("homepage.home"))


@BP.route("/contributors")
def contributors():
    return render_template("contributors.html")


@BP.route("/publications")
def publications():
    return render_template("publications.html")

quasimodo_website/taboo/__init__.py
from quasimodo_website.taboo import routes

quasimodo_website/taboo/blueprint.py
from flask import Blueprint

BP = Blueprint('taboo', __name__)

quasimodo_website/taboo/routes.py
import os
import random

from flask import session, request, jsonify, render_template, current_app
from sqlalchemy import func

from quasimodo_website.models import Fact
from quasimodo_website.models.subject_form import SubjectForm
from quasimodo_website.models.taboo_card import TabooCard
from quasimodo_website.taboo.blueprint import BP
from quasimodo_website import DB


@BP.route("/")
def home():
    return render_template("taboo.html")


@BP.route("/start_new_game")
def start_new_game():
    session['words_given'] = []
    max_row = TabooCard.query.count()
    if max_row == 0:
        return jsonify({"error": "No cards"})
    rand_number = random.randrange(0, max_row)
    random_card = TabooCard.query[rand_number]
    session["word_to_guess"] = random_card.word_to_guess
    session["forbidden_words"] = random_card.get_forbidden_words()
    session["wrongly_guessed"] = []
    return jsonify({"word_to_guess": random_card.word_to_guess,
                    "forbidden_words": random_card.get_forbidden_words()})


def try_to_guess(words_given, wrongly_guessed,
                 score_criterion=Fact.plausibility):
    query = None
    if not words_given:
        return "No idea"
    for word in words_given:
        sub_query = Fact.query.filter(Fact.object.like("%" + word + "%")) \
            .with_entities(Fact.subject, score_criterion)
        if query is None:
            query = sub_query
        else:
            query = query.union(sub_query)
    query = query.filter(Fact.subject.notin_(wrongly_guessed)) \
        .group_by(Fact.subject)
    query = query.with_entities(Fact.subject, func.max(score_criterion))
    results = query.all()
    if not results:
        return "No idea"
    best = max(results, key=lambda x: x[1])
    return best[0]


def preprocess_given_word(given_word):
    return given_word.lower()


def are_too_similar(first_word, second_word):
    return first_word in second_word or second_word in first_word


@BP.route("/give_word")
def give_word():
    given_word = request.args.get('word', None, type=str)
    if given_word is not None:
        given_word = preprocess_given_word(given_word)
        words_given = session.get("words_given", [])
        word_to_guess = session.get("word_to_guess", "")
        current_app.logger.info("Taboo: word to guess: " +
                                word_to_guess +
                                " word given: " + given_word)
        if are_too_similar(word_to_guess, given_word):
            return jsonify({"error": "The given word is too similar "
                                     "to the word to guess"})
        for forbidden_word in session.get("forbidden_words", []):
            if are_too_similar(given_word, forbidden_word):
                return jsonify({"error": "The given word is too similar "
                                         "to the forbidden word: "
                                         + str(forbidden_word)})
        if given_word in words_given:
            return jsonify({"error": "Word already given"})
        session["words_given"] = words_given
        session["words_given"].append(given_word)
    return jsonify({})


@BP.route("/guess_word")
def guess_word():
    guessed = try_to_guess(session.get("words_given", []),
                           session.get("wrongly_guessed", []))
    is_correct = guessed == session.get("word_to_guess", "")
    if not is_correct:
        session["wrongly_guessed"] = session.get("wrongly_guessed", [])
        session["wrongly_guessed"].append(guessed)
    current_app.logger.info("Guessed: " + guessed +
                            " for: " +
                            ", ".join(session.get("words_given", [])))
    return jsonify({"guessed": guessed,
                    "is_correct": is_correct})


@BP.route("/get_wrongly_guessed")
def get_wrongly_guessed():
    return jsonify(session.get("wrongly_guessed", []))


@BP.route("/get_given_words")
def get_given_words():
    return jsonify(session.get("words_given", []))


@BP.route("/get_word_to_guess")
def get_word_to_guess():
    return jsonify({"word_to_guess": session.get("word_to_guess", "")})


@BP.route("/get_forbidden_words")
def get_forbidden_words():
    return jsonify({"forbidden_words": session.get("forbidden_words", [])})


@BP.route("/initialize")
def initialize():
    n_facts = TabooCard.query.count()
    if n_facts == 0:
        cards = []
        with open(os.path.abspath(os.path.dirname(__file__)) +
                  "/../static/data/taboo.tsv") as taboo_card_file:
            for line in taboo_card_file:
                line = line.strip().split("\t")
                taboo_card = TabooCard(word_to_guess=line[0])
                taboo_card.set_forbidden_words(line[1:])
                cards.append(taboo_card)
        DB.session.add_all(cards)
        DB.session.commit()
    return jsonify({"status": "Done"})


@BP.route("/generate_card", methods=["GET", "POST"])
def generate_card():
    form = SubjectForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data.strip().lower()
    else:
        subject = request.args.get('subject', None, type=str)
    format = request.args.get("format", "html", type=str)
    if subject is None:
        if format == "json":
            return jsonify({})
        return render_template("taboo_card.html", form=form)
    n_words = request.args.get("n_words", 5, type=int)
    subjects = Fact.query.with_entities(Fact.subject).distinct(Fact.subject).subquery()
    objects = Fact.query.with_entities(Fact.object)\
        .filter(Fact.subject == subject) \
        .filter(Fact.object.in_(subjects))\
        .group_by(Fact.object)\
        .order_by(func.sum(Fact.plausibility).desc())\
        .limit(n_words)\
        .all()
    objects = [x[0] for x in objects]
    if format == "json":
        return jsonify(objects)
    return render_template("taboo_card.html",
                           subject=subject,
                           card=objects,
                           form=form)

quasimodo_website/templates/codenames.html
{% extends "homepage.html" %}

{% block inner_content %}

<div class="container" id="cards-codenames">

    <p>{{ message }}</p>

    <p><a href="{{ url_for('codenames.pass_turn') }}">Pass</a></p>

    {% include '_anonymous_codenames.html' %}

    <br>
    <br>
    <h2>Description</h2><br>
    Codenames is a game designed by Vlaada Chvátil. It opposes two teams that must find their special agent before the other team. The agents are hidden behind codenames, which are simple words. Each team has a spymaster which must give a clue to the rest of the team (the operatives) to help us reveal the spies. For example, a spymaster can say <i>blue, 2</i> to help its companion guess the words <i>sky</i> and <i>sea</i>. The choice of the word must be made very carefully not to discover the agents of the other team.
    <br>
    In 2019, the Foundation of Digital Games conference hosted a competition: <a href="https://sites.google.com/view/the-codenames-ai-competition">The Codenames AI competition</a>. However, we were not able to find the results of this competition. The presenters suggested that people should use word embeddings. This solution can be powerful when we make AI play against each other. However, the clues can become incomprehensible for humans.
    <br>
Instead, we propose a solution based on Quasimodo to generate clues. We consider that the words to guess are subjects. Then, we take the object associated with the more subjects that has a score above a certain threshold and does not appear for the wrong subjects.
<br>
In the demonstration scenario, the user plays the role of the operative. He receives clues and must click on the potential agents. He plays against a bot which simply guesses one right word per turn. Vlaada Chvátil suggests this strategy for games with two players.

</div>

{% endblock %}

{% block scripts %}

    {{super()}}

{% endblock %}

quasimodo_website/templates/codenames_full.html
{% extends "homepage.html" %}

{% block inner_content %}

<div class="container" id="cards-codenames">

    <p>{{ message }}</p>

    <p><a href="{{ url_for('codenames.home') }}">New Game</a></p>

    {% include '_spy_codenames.html' %}


</div>

{% endblock %}

{% block scripts %}

    {{super()}}

{% endblock %}

quasimodo_website/templates/homepage.html
{% extends "bootstrap/base.html" %}

{% block title %}
    {% if title_page %}
        QUASIMODO - {{ title_page }}
    {% else %}
        QUASIMODO
    {% endif %}
{% endblock %}

{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('homepage.home') }}">QUASIMODO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('homepage.home') }}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('explorer.home') }}">Explorer</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('explorer.search') }}">Search</a></li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              SparQL
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/sparql">UI</a>
                <a class="dropdown-item" href="/query">Endpoint</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Use Cases
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('taboo.home') }}">Play Taboo </a>
                <a class="dropdown-item" href="{{ url_for('taboo.generate_card') }}">Generate Taboo Card</a>
                <a class="dropdown-item" href="{{ url_for('codenames.home') }}">Codenames</a>
                <a class="dropdown-item" href="{{ url_for('question_answering.question_page') }}">Question Answering</a>
            </div>
        </li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('tasks.home') }}">Live Pipeline Examples</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('homepage.publications') }}">Publications</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('homepage.contributors') }}">Contributors</a></li>
    </ul>
  </div>
</nav>

{% endblock %}


{% block content %}
    <br>
    {% block inner_content %}
    {% endblock %}

    <br><br>

{% endblock %}

{% block scripts %}
    <script src="https://kit.fontawesome.com/9a16929992.js" crossorigin="anonymous"></script>
{% endblock %}

{% block head %}
    {{super()}}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock %}

{% block styles %}

  {{super()}}
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

{% endblock %}

quasimodo_website/templates/main_page.html
{% extends "homepage.html" %}

{% block inner_content %}

<div class="container">

    <h1>Welcome to Quasimodo demo</h1>

    <br>

    <h3>Description</h3>

    <p>
        Quasimodo is an open-source commonsense knowledge base designed to get relevant properties about entities.
    </p>


    <h3>Abstract</h3>

    <p>
        Commonsense knowledge about object properties, human behavior and general concepts is crucial for robust AI applications.
        However, automatic acquisition of this knowledge is challenging because of sparseness and bias in online sources.
        This paper presents Quasimodo, a methodology and tool suite for distilling commonsense properties from non-standard web sources.
        We devise novel ways of tapping into search-engine query logs and QA forums, and combining the resulting candidate assertions with statistical
        cues from encyclopedias, books and image tags in a corroboration step. Unlike prior work on commonsense knowledge bases,
        Quasimodo focuses on salient properties that are typically associated with certain objects or concepts.
        Extensive evaluations, including extrinsic use-case studies, show that Quasimodo provides better coverage than
        state-of-the-art baselines with comparable quality.
    </p>


    <h3>Full Paper</h3>

    The full paper is freely available on <a href="https://arxiv.org/abs/1905.10989">Arxiv</a>.
    More related papers can be found on <a href="{{ url_for('homepage.publications') }}">the publication page.</a>

    <br><br>

    <h3>Data</h3>

    <p>The raw data of Quasimodo can be found on the
        <a href="https://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/commonsense/quasimodo/">
            Max Planck Institute D5's website
        </a>.

        <br>

        Otherwise, the dataset can be explored in the <a href="{{ url_for('explorer.home') }}">Explorer section</a>.
        We also added the possibility to search for specific subject, property and object in the
        <a href="{{ url_for('explorer.search') }}">Search section</a>. Here are some examples of searches:
    </p>
    <ul>
        <li>For subject <a href="{{ url_for('explorer.home', subject='elephant') }}">elephant</a></li>
        <li>For subject <a href="{{ url_for('explorer.home', subject='musician') }}">musician</a></li>
        <li>For predicate <a href="{{ url_for('explorer.home', predicate='has_color') }}">has_color</a></li>
        <li>For object <a href="{{ url_for('explorer.home', object='music') }}">music</a></li>
    </ul>

    <p>
        In addition, it is possible to access to more details for a given fact, such as <a href="{{ url_for('explorer.get_fact', id='1') }}">this one</a>.
    </p>


    <h3>Code</h3>

    The code for running Quasimodo is available on <a href="https://github.com/Aunsiels/CSK">Github</a>.
    The code for running Quasimodo demo is also available on Github <a href="https://github.com/Aunsiels/demo_quasimodo">Github</a>.


    <h3>Pipeline</h3>

    Quasimodo pipeline can be summarize by the following diagram. For more information, please refer to our paper.

    <br><br>

    <div class="row">
            <img src="{{ url_for('static', filename='img/pipeline.png') }}" alt="Pipeline" class="img-responsive">
    </div>

    <br>

    Examples of pipeline execution for a single subject can be found on <a href="{{ url_for('tasks.home') }}">the dedicated page</a>.

</div>



{% endblock %}

quasimodo_website/templates/search.html
{% extends "explorer.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block search %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

quasimodo_website/templates/taboo.html
{% extends "homepage.html" %}

{% block inner_content %}

<div class="container" onload="load_new_card('{{ url_for('taboo.start_new_game') }}')">

    <div class="row">
        <div class="col" align="center">
            <h1>Welcome to play Taboo!</h1>
            <br>
        </div>
    </div>

    <div class="row">

        <div class="col">
            <div class="card d-none" style="width: 18rem;" id="tabooCard">
                <div class="card-header">
                    <p id="card_title"></p>
                </div>
                <ul class="list-group list-group-flush" id="forbidden_words">
                      <li class="list-group-item"><p id="forbidden_word0"></p></li>
                      <li class="list-group-item"><p id="forbidden_word1"></p></li>
                      <li class="list-group-item"><p id="forbidden_word2"></p></li>
                      <li class="list-group-item"><p id="forbidden_word3"></p></li>
                      <li class="list-group-item"><p id="forbidden_word4"></p></li>
                </ul>
            </div>
        </div>

        <div class="col-sm frame">
            <ul id="chat-list" class="chat"></ul>
            <div>
                <div class="msj-rta macro" style="margin:auto">
                    <div class="text text-r" style="background:whitesmoke !important">
                        <input class="mytext" placeholder="Give a clue" data-url="{{ url_for('taboo.give_word') }}"/>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col" align="center">
            <br>
            <button type="button" class="btn btn-dark" onclick="load_new_card('{{ url_for('taboo.start_new_game') }}')" id="new-game">New Game</button>
            <button type="button" class="btn btn-dark" onclick="try_to_guess('{{ url_for('taboo.guess_word') }}')" id="guess-word">Guess Word</button>
        </div>
    </div>
    <div class="row">
        <br>
        <h2>Description</h2>
        <br>
        Taboo is a game in which a player must make other players guess a word without using a list of forbidden words. In this demo, we provide an interface to play Taboo with Quasimodo. When a user starts a new game, the web portal sends him a card. Then they must use a chat interface to give clue words to Quasimodo. Every time the user presses the Make a Guess button, the system tries to a find a relevant word.
        <br>
The algorithm used in the back end is simple. First, the database is filtered using the words given by the user. Then, we group the results by subjects, and we aggregate the scores using a sum or a max function, for example. We finally return the best subject, under the condition that we never tried it before.
<br>
In addition to this game, we also provide the functionality to generate Taboo cards for any subject. We perform this generation by taking the most relevant objects associated with a subject by combining the scores.
    </div>

</div>


{% endblock %}

{% block styles %}

  {{super()}}
  <link href="{{ url_for('static', filename='css/chat.css') }}" rel="stylesheet">

{% endblock %}

{% block scripts %}

    {{super()}}

    <script src="{{ url_for('static', filename='js/chat.js') }}"></script>
    <script src="{{ url_for('static', filename='js/taboo.js') }}"></script>


{% endblock %}